local utils = require('lualine.utils.utils')
describe('utils tests', function()
  describe('test1', function()
    it('aaa', function()
      utils.save_highlight('a')
      assert.are.same(utils.loaded_highlights['a'], true)
    end)
  end)
end)
